import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const root = path.resolve(__dirname, "..");
const sourceThemesPath = path.join(root, "src", "theme", "themes.json");
const targetDir = path.join(root, "public", "config-builder");
const targetThemesPath = path.join(targetDir, "themes.json");
const targetThemeFontsCssPath = path.join(targetDir, "theme-fonts.css");

const baseHostedFamilies = new Set(["Inter", "Playfair Display"]);

const googleFamilyQueryByName = new Map([
    ["Cormorant Garamond", "family=Cormorant+Garamond:wght@400;500;600;700"],
    ["Manrope", "family=Manrope:wght@400;500;600;700"],
    ["Bodoni Moda", "family=Bodoni+Moda:opsz,wght@6..96,400;500;600"],
    ["Source Sans 3", "family=Source+Sans+3:wght@400;500;600;700"],
    ["Fraunces", "family=Fraunces:opsz,wght@9..144,400;500;600"],
    ["DM Sans", "family=DM+Sans:wght@400;500;700"],
    ["Instrument Serif", "family=Instrument+Serif:ital@0;1"],
]);

function firstFamilyFromStack(stack) {
    if (typeof stack !== "string") {
        return "";
    }

    const first = stack.split(",")[0]?.trim() || "";
    return first.replace(/^['"]|['"]$/g, "");
}

function googleFamilyQueryFor(familyName) {
    const override = googleFamilyQueryByName.get(familyName);
    if (override) {
        return override;
    }

    const encoded = familyName.trim().split(/\s+/).join("+");
    return `family=${encoded}:wght@400;500;600;700`;
}

function buildThemeFontsCss(themes) {
    const families = new Set();

    for (const theme of themes) {
        const display = firstFamilyFromStack(theme?.fonts?.display);
        const sans = firstFamilyFromStack(theme?.fonts?.sans);
        if (display) families.add(display);
        if (sans) families.add(sans);
    }

    const externalFamilies = [...families]
        .filter((family) => !baseHostedFamilies.has(family))
        .sort((a, b) => a.localeCompare(b));

    if (externalFamilies.length === 0) {
        return "/* Auto-generated by scripts/sync-themes.mjs. No external theme fonts required. */\n";
    }

    const query = externalFamilies
        .map((family) => googleFamilyQueryFor(family))
        .join("&");

    return [
        "/* Auto-generated by scripts/sync-themes.mjs. Do not edit manually. */",
        `@import url("https://fonts.googleapis.com/css2?${query}&display=swap");`,
        "",
    ].join("\n");
}

await mkdir(targetDir, { recursive: true });
await copyFile(sourceThemesPath, targetThemesPath);

const themesRaw = await readFile(sourceThemesPath, "utf8");
const themes = JSON.parse(themesRaw);
const themeFontsCss = buildThemeFontsCss(themes);
await writeFile(targetThemeFontsCssPath, themeFontsCss, "utf8");

console.log(`Synced themes to ${targetThemesPath}`);
console.log(`Synced theme fonts to ${targetThemeFontsCssPath}`);
